version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    # Expose internal port only; Traefik will route externally via 80/443
    expose:
      - "8080"
    environment:
      - NODE_ENV=production
    command: ["http-server", "./dist", "-p", "8080"]
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      # HTTPS router (replace certresolver if Dokploy names it differently e.g. 'letsencrypt' or 'production')
      - traefik.http.routers.portfolio.rule=Host(`jorgedelgadillo.com`,`www.jorgedelgadillo.com`)
      - traefik.http.routers.portfolio.entrypoints=websecure
      - traefik.http.routers.portfolio.tls=true
      - traefik.http.routers.portfolio.tls.certresolver=letsencrypt
      - traefik.http.services.portfolio.loadbalancer.server.port=8080
      # HTTP (80) router that redirects to HTTPS
      - traefik.http.routers.portfolio-http.rule=Host(`jorgedelgadillo.com`,`www.jorgedelgadillo.com`)
      - traefik.http.routers.portfolio-http.entrypoints=web
      - traefik.http.routers.portfolio-http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

volumes:
  node_modules:
\n+networks:
  dokploy-network:
    external: true